### ISSUE TITLE
Assignment2

### ISSUE THREAD

**Issue by blackboxlogic** [mgeezzyy/Cos470#2]
Regarding:
https://github.com/mgeezzyy/Cos470/blob/ecab70d02f37613eee52bd367d73f0910ebf39e5/Assignment2/DollarAddresses/appsettings.json#L3
I see that plus sign there, pretending you don't need to URL encode your parameters.

Regarding:
https://github.com/mgeezzyy/Cos470/blob/ecab70d02f37613eee52bd367d73f0910ebf39e5/Assignment2/DollarAddresses/DollarAddresses/Program.cs#L24
This won't work when I check out your code on my computer because the path is different. I suggest putting the config file as part of the project and having it copied to the output directory.

**Comment by mgeezzyy** [comment]
@blackboxlogic I added (by clicking "add" in the project directory) the config to the project dir but the program is trying to look for the file somewhere in the bin directory and not the "main" project directory. Is there a way to specify where the program looks for files?

**Comment by mgeezzyy** [comment]
@blackboxlogic nvm. I figured it out.
